site_name: pism documentation
site_description: A Python project to retrieve data from the NIST Atomic Spectra Database (ASD), using caching for fast, efficient data handling
repo_name: pism
repo_url: https://github.com/mikegrudic/pism

docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github-alt
    logo: fontawesome/solid/egg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.footer
    - toc.integrate
    - toc.follow
    - content.code.copy

watch:
- src/pism

# Extensions
plugins:
  # Built-in
  search: {}
  autorefs: {}
  # Extra
  include-markdown:
    rewrite_relative_urls: true
  mike:
    alias_type: copy
  git-revision-date-localized:
    exclude:
      - reference/*
    fallback_to_build_date: true
    enable_creation_date: true
#  gen-files:
#    scripts:
#      - docs/assets/scripts/gen_ref_pages.py
  literate-nav:
    nav_file: SUMMARY.md
  section-index: {}
  mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths:
          - src
        options:
          heading_level: 1
          summary: true
          docstring_style: google
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: no
          show_submodules: no
          # Headings
          show_root_heading: true
          show_root_full_path: true
          show_root_members_full_path: false
          # Docstrings
          show_if_no_docstring: true
          show_docstring_attributes: false
          show_docstring_functions: true
          # Signatures/annotations
          annotations_path: brief
          separate_signature: true
          line_length: 80
          show_signature_annotations: true
          # Other
          show_bases: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
  mkdocs-jupyter:
    include_requirejs: true
    custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe" #https://github.com/danielfrg/mkdocs-jupyter/issues/227
    include_source: true
    include: ["*.ipynb"]
    ignore: ["*/.ipynb_checkpoints/*.ipynb"]

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: mikegrudic
      repo: pism
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mikegrudic/pism

extra_javascript:
  - assets/javascript/mathjax.js
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

nav:
  - my_page.md
#  - schema.md
#  - Examples: examples.ipynb
#  - Citing: citing.md
  # defer to gen-files + literate-nav
#  - Reference: reference/pism/
#  - Changelog: changelog.md
#  - License: license.md