#pragma once
// Runtime table interpolation for large 2D/3D tables loaded from HDF5.
// Auto-generated by jaco — not intended to be modified by hand.

#include <hdf5.h>
#include <stdlib.h>
#include <math.h>

#ifdef __CUDACC__
#define JACO_TABLE_FUNC __host__ __device__ __forceinline__
#define JACO_HOST_FUNC __host__
#else
#define JACO_TABLE_FUNC static inline
#define JACO_HOST_FUNC
#endif

// --- 2D Table ---

typedef struct {
    double *data;      // row-major [n0 * n1]
    double min0, max0; // axis 0 range
    double min1, max1; // axis 1 range
    int n0, n1;        // axis sizes
    int log0, log1;    // 1 if axis is log-spaced
} JacoTable2D;

JACO_TABLE_FUNC double jaco_table2d_interp(double x0, double x1, const JacoTable2D* t) {
    // Map to normalized coordinates [0, n-1]
    double v0 = t->log0 ? log(x0) : x0;
    double v1 = t->log1 ? log(x1) : x1;
    double lo0 = t->log0 ? log(t->min0) : t->min0;
    double hi0 = t->log0 ? log(t->max0) : t->max0;
    double lo1 = t->log1 ? log(t->min1) : t->min1;
    double hi1 = t->log1 ? log(t->max1) : t->max1;

    double fx = (v0 - lo0) / (hi0 - lo0) * (t->n0 - 1);
    double fy = (v1 - lo1) / (hi1 - lo1) * (t->n1 - 1);

    // Clamp
    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    double tx = fx - ix;
    double ty = fy - iy;

    // Bilinear interpolation
    double f00 = t->data[ix * t->n1 + iy];
    double f10 = t->data[(ix + 1) * t->n1 + iy];
    double f01 = t->data[ix * t->n1 + (iy + 1)];
    double f11 = t->data[(ix + 1) * t->n1 + (iy + 1)];

    return (1 - tx) * (1 - ty) * f00 + tx * (1 - ty) * f10
         + (1 - tx) * ty * f01 + tx * ty * f11;
}

// Partial derivatives of bilinear interpolation (for symbolic Jacobian path)
JACO_TABLE_FUNC double jaco_table2d_interp_dx(double x0, double x1, const JacoTable2D* t) {
    double v0 = t->log0 ? log(x0) : x0;
    double v1 = t->log1 ? log(x1) : x1;
    double lo0 = t->log0 ? log(t->min0) : t->min0;
    double hi0 = t->log0 ? log(t->max0) : t->max0;
    double lo1 = t->log1 ? log(t->min1) : t->min1;
    double hi1 = t->log1 ? log(t->max1) : t->max1;

    double dx = (hi0 - lo0) / (t->n0 - 1);
    double dy = (hi1 - lo1) / (t->n1 - 1);
    double fx = (v0 - lo0) / dx;
    double fy = (v1 - lo1) / dy;
    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    double ty = fy - iy;

    double f00 = t->data[ix * t->n1 + iy];
    double f10 = t->data[(ix + 1) * t->n1 + iy];
    double f01 = t->data[ix * t->n1 + (iy + 1)];
    double f11 = t->data[(ix + 1) * t->n1 + (iy + 1)];

    double df_dtx = -(1-ty)*f00 + (1-ty)*f10 - ty*f01 + ty*f11;
    double dv0_dx0 = t->log0 ? 1.0 / x0 : 1.0;
    return df_dtx / dx * dv0_dx0;
}

JACO_TABLE_FUNC double jaco_table2d_interp_dy(double x0, double x1, const JacoTable2D* t) {
    double v0 = t->log0 ? log(x0) : x0;
    double v1 = t->log1 ? log(x1) : x1;
    double lo0 = t->log0 ? log(t->min0) : t->min0;
    double hi0 = t->log0 ? log(t->max0) : t->max0;
    double lo1 = t->log1 ? log(t->min1) : t->min1;
    double hi1 = t->log1 ? log(t->max1) : t->max1;

    double dx = (hi0 - lo0) / (t->n0 - 1);
    double dy = (hi1 - lo1) / (t->n1 - 1);
    double fx = (v0 - lo0) / dx;
    double fy = (v1 - lo1) / dy;
    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    double tx = fx - ix;

    double f00 = t->data[ix * t->n1 + iy];
    double f10 = t->data[(ix + 1) * t->n1 + iy];
    double f01 = t->data[ix * t->n1 + (iy + 1)];
    double f11 = t->data[(ix + 1) * t->n1 + (iy + 1)];

    double df_dty = -(1-tx)*f00 - tx*f10 + (1-tx)*f01 + tx*f11;
    double dv1_dx1 = t->log1 ? 1.0 / x1 : 1.0;
    return df_dty / dy * dv1_dx1;
}

// --- 3D Table ---

typedef struct {
    double *data;      // row-major [n0 * n1 * n2]
    double min0, max0;
    double min1, max1;
    double min2, max2;
    int n0, n1, n2;
    int log0, log1, log2;
} JacoTable3D;

JACO_TABLE_FUNC double jaco_table3d_interp(double x0, double x1, double x2, const JacoTable3D* t) {
    double v0 = t->log0 ? log(x0) : x0;
    double v1 = t->log1 ? log(x1) : x1;
    double v2 = t->log2 ? log(x2) : x2;
    double lo0 = t->log0 ? log(t->min0) : t->min0;
    double hi0 = t->log0 ? log(t->max0) : t->max0;
    double lo1 = t->log1 ? log(t->min1) : t->min1;
    double hi1 = t->log1 ? log(t->max1) : t->max1;
    double lo2 = t->log2 ? log(t->min2) : t->min2;
    double hi2 = t->log2 ? log(t->max2) : t->max2;

    double fx = (v0 - lo0) / (hi0 - lo0) * (t->n0 - 1);
    double fy = (v1 - lo1) / (hi1 - lo1) * (t->n1 - 1);
    double fz = (v2 - lo2) / (hi2 - lo2) * (t->n2 - 1);

    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;
    if (fz < 0) fz = 0; if (fz > t->n2 - 1) fz = t->n2 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    int iz = (int)fz; if (iz >= t->n2 - 1) iz = t->n2 - 2;
    double tx = fx - ix, ty = fy - iy, tz = fz - iz;

    int s1 = t->n2, s0 = t->n1 * t->n2;
    #define D(i,j,k) t->data[(ix+(i))*s0 + (iy+(j))*s1 + (iz+(k))]
    double result =
        (1-tx)*(1-ty)*(1-tz)*D(0,0,0) + tx*(1-ty)*(1-tz)*D(1,0,0)
      + (1-tx)*ty*(1-tz)*D(0,1,0)     + tx*ty*(1-tz)*D(1,1,0)
      + (1-tx)*(1-ty)*tz*D(0,0,1)     + tx*(1-ty)*tz*D(1,0,1)
      + (1-tx)*ty*tz*D(0,1,1)         + tx*ty*tz*D(1,1,1);
    #undef D
    return result;
}

// --- HDF5 Loaders ---

JACO_HOST_FUNC static JacoTable2D jaco_table2d_load(const char* filename) {
    JacoTable2D t;
    hid_t file = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

    hid_t dset = H5Dopen(file, "data", H5P_DEFAULT);
    hid_t space = H5Dget_space(dset);
    hsize_t dims[2];
    H5Sget_simple_extent_dims(space, dims, NULL);
    t.n0 = (int)dims[0]; t.n1 = (int)dims[1];
    t.data = (double*)malloc(t.n0 * t.n1 * sizeof(double));
    H5Dread(dset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, t.data);
    H5Sclose(space); H5Dclose(dset);

    // Read axis endpoints
    double ax0[2], ax1[2];
    hid_t a0 = H5Dopen(file, "axis0", H5P_DEFAULT);
    hid_t a0s = H5Dget_space(a0);
    hsize_t start = 0, count = 1;
    H5Sselect_hyperslab(a0s, H5S_SELECT_SET, &start, NULL, &count, NULL);
    hid_t memspace1 = H5Screate_simple(1, &count, NULL);
    H5Dread(a0, H5T_NATIVE_DOUBLE, memspace1, a0s, H5P_DEFAULT, &ax0[0]);
    start = dims[0] - 1;
    H5Sselect_hyperslab(a0s, H5S_SELECT_SET, &start, NULL, &count, NULL);
    H5Dread(a0, H5T_NATIVE_DOUBLE, memspace1, a0s, H5P_DEFAULT, &ax0[1]);
    H5Sclose(a0s); H5Dclose(a0);

    hid_t a1 = H5Dopen(file, "axis1", H5P_DEFAULT);
    hid_t a1s = H5Dget_space(a1);
    start = 0;
    H5Sselect_hyperslab(a1s, H5S_SELECT_SET, &start, NULL, &count, NULL);
    H5Dread(a1, H5T_NATIVE_DOUBLE, memspace1, a1s, H5P_DEFAULT, &ax1[0]);
    start = dims[1] - 1;
    H5Sselect_hyperslab(a1s, H5S_SELECT_SET, &start, NULL, &count, NULL);
    H5Dread(a1, H5T_NATIVE_DOUBLE, memspace1, a1s, H5P_DEFAULT, &ax1[1]);
    H5Sclose(a1s); H5Dclose(a1); H5Sclose(memspace1);

    t.min0 = ax0[0]; t.max0 = ax0[1];
    t.min1 = ax1[0]; t.max1 = ax1[1];

    // Read log flags from attributes
    t.log0 = 0; t.log1 = 0;
    if (H5Aexists(file, "axis0_log")) {
        hid_t attr = H5Aopen(file, "axis0_log", H5P_DEFAULT);
        int val; H5Aread(attr, H5T_NATIVE_INT, &val); t.log0 = val; H5Aclose(attr);
    }
    if (H5Aexists(file, "axis1_log")) {
        hid_t attr = H5Aopen(file, "axis1_log", H5P_DEFAULT);
        int val; H5Aread(attr, H5T_NATIVE_INT, &val); t.log1 = val; H5Aclose(attr);
    }

    H5Fclose(file);
    return t;
}

JACO_HOST_FUNC static JacoTable3D jaco_table3d_load(const char* filename) {
    JacoTable3D t;
    hid_t file = H5Fopen(filename, H5F_ACC_RDONLY, H5P_DEFAULT);

    hid_t dset = H5Dopen(file, "data", H5P_DEFAULT);
    hid_t space = H5Dget_space(dset);
    hsize_t dims[3];
    H5Sget_simple_extent_dims(space, dims, NULL);
    t.n0 = (int)dims[0]; t.n1 = (int)dims[1]; t.n2 = (int)dims[2];
    t.data = (double*)malloc(t.n0 * t.n1 * t.n2 * sizeof(double));
    H5Dread(dset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, t.data);
    H5Sclose(space); H5Dclose(dset);

    double ax[2];
    hsize_t start, count = 1;
    hid_t memspace1 = H5Screate_simple(1, &count, NULL);

    for (int i = 0; i < 3; i++) {
        char name[16]; snprintf(name, sizeof(name), "axis%d", i);
        hid_t ai = H5Dopen(file, name, H5P_DEFAULT);
        hid_t ais = H5Dget_space(ai);
        start = 0;
        H5Sselect_hyperslab(ais, H5S_SELECT_SET, &start, NULL, &count, NULL);
        H5Dread(ai, H5T_NATIVE_DOUBLE, memspace1, ais, H5P_DEFAULT, &ax[0]);
        start = dims[i] - 1;
        H5Sselect_hyperslab(ais, H5S_SELECT_SET, &start, NULL, &count, NULL);
        H5Dread(ai, H5T_NATIVE_DOUBLE, memspace1, ais, H5P_DEFAULT, &ax[1]);
        H5Sclose(ais); H5Dclose(ai);
        switch(i) {
            case 0: t.min0 = ax[0]; t.max0 = ax[1]; break;
            case 1: t.min1 = ax[0]; t.max1 = ax[1]; break;
            case 2: t.min2 = ax[0]; t.max2 = ax[1]; break;
        }
    }
    H5Sclose(memspace1);

    t.log0 = 0; t.log1 = 0; t.log2 = 0;
    const char* lognames[] = {"axis0_log", "axis1_log", "axis2_log"};
    int* logflags[] = {&t.log0, &t.log1, &t.log2};
    for (int i = 0; i < 3; i++) {
        if (H5Aexists(file, lognames[i])) {
            hid_t attr = H5Aopen(file, lognames[i], H5P_DEFAULT);
            int val; H5Aread(attr, H5T_NATIVE_INT, &val); *logflags[i] = val; H5Aclose(attr);
        }
    }

    H5Fclose(file);
    return t;
}

#ifdef __CUDACC__
// Copy a loaded table to device memory
__host__ static JacoTable2D jaco_table2d_to_device(const JacoTable2D* host) {
    JacoTable2D dev = *host;
    size_t bytes = host->n0 * host->n1 * sizeof(double);
    cudaMalloc(&dev.data, bytes);
    cudaMemcpy(dev.data, host->data, bytes, cudaMemcpyHostToDevice);
    return dev;
}

__host__ static JacoTable3D jaco_table3d_to_device(const JacoTable3D* host) {
    JacoTable3D dev = *host;
    size_t bytes = host->n0 * host->n1 * host->n2 * sizeof(double);
    cudaMalloc(&dev.data, bytes);
    cudaMemcpy(dev.data, host->data, bytes, cudaMemcpyHostToDevice);
    return dev;
}
#endif
