#pragma once
// Forward-mode autodiff dual number type for Jacobian computation.
// Auto-generated by jaco — not intended to be modified by hand.

#include <cmath>

#ifdef __CUDACC__
#define JACO_DUAL_FUNC __host__ __device__ __forceinline__
#else
#define JACO_DUAL_FUNC inline
#endif

struct dual {
    double val;
    double dot;

    JACO_DUAL_FUNC dual(double v = 0.0, double d = 0.0) : val(v), dot(d) {}
};

// Arithmetic
JACO_DUAL_FUNC dual operator+(dual a, dual b) { return {a.val + b.val, a.dot + b.dot}; }
JACO_DUAL_FUNC dual operator-(dual a, dual b) { return {a.val - b.val, a.dot - b.dot}; }
JACO_DUAL_FUNC dual operator-(dual a) { return {-a.val, -a.dot}; }
JACO_DUAL_FUNC dual operator*(dual a, dual b) { return {a.val * b.val, a.val * b.dot + a.dot * b.val}; }
JACO_DUAL_FUNC dual operator/(dual a, dual b) {
    return {a.val / b.val, (a.dot * b.val - a.val * b.dot) / (b.val * b.val)};
}

// Mixed dual-double arithmetic
JACO_DUAL_FUNC dual operator+(double a, dual b) { return dual(a) + b; }
JACO_DUAL_FUNC dual operator+(dual a, double b) { return a + dual(b); }
JACO_DUAL_FUNC dual operator-(double a, dual b) { return dual(a) - b; }
JACO_DUAL_FUNC dual operator-(dual a, double b) { return a - dual(b); }
JACO_DUAL_FUNC dual operator*(double a, dual b) { return dual(a) * b; }
JACO_DUAL_FUNC dual operator*(dual a, double b) { return a * dual(b); }
JACO_DUAL_FUNC dual operator/(double a, dual b) { return dual(a) / b; }
JACO_DUAL_FUNC dual operator/(dual a, double b) { return a / dual(b); }

// Comparison (by value only, for branching in interp)
JACO_DUAL_FUNC bool operator<=(dual a, double b) { return a.val <= b; }
JACO_DUAL_FUNC bool operator>=(dual a, double b) { return a.val >= b; }
JACO_DUAL_FUNC bool operator<(dual a, double b) { return a.val < b; }
JACO_DUAL_FUNC bool operator>(dual a, double b) { return a.val > b; }
JACO_DUAL_FUNC bool operator<=(double a, dual b) { return a <= b.val; }
JACO_DUAL_FUNC bool operator>=(double a, dual b) { return a >= b.val; }

// Math functions
JACO_DUAL_FUNC dual exp(dual a) { double e = std::exp(a.val); return {e, e * a.dot}; }
JACO_DUAL_FUNC dual log(dual a) { return {std::log(a.val), a.dot / a.val}; }
JACO_DUAL_FUNC dual sqrt(dual a) { double s = std::sqrt(a.val); return {s, 0.5 * a.dot / s}; }
JACO_DUAL_FUNC dual tanh(dual a) { double t = std::tanh(a.val); return {t, (1.0 - t * t) * a.dot}; }
JACO_DUAL_FUNC dual fabs(dual a) { return {std::fabs(a.val), a.val >= 0 ? a.dot : -a.dot}; }
JACO_DUAL_FUNC dual fmin(dual a, dual b) { return a.val <= b.val ? a : b; }
JACO_DUAL_FUNC dual fmax(dual a, dual b) { return a.val >= b.val ? a : b; }

// pow(dual, dual)
JACO_DUAL_FUNC dual pow(dual a, dual b) {
    double v = std::pow(a.val, b.val);
    return {v, v * (b.dot * std::log(a.val) + b.val * a.dot / a.val)};
}
// pow(dual, double)
JACO_DUAL_FUNC dual pow(dual a, double b) {
    double v = std::pow(a.val, b);
    return {v, b * std::pow(a.val, b - 1.0) * a.dot};
}
// pow(dual, int)
JACO_DUAL_FUNC dual pow(dual a, int b) { return pow(a, static_cast<double>(b)); }
// pow(double, dual)
JACO_DUAL_FUNC dual pow(double a, dual b) {
    double v = std::pow(a, b.val);
    return {v, v * std::log(a) * b.dot};
}

// Dual-aware piecewise-linear interpolation.
// xp and yp are constant double arrays; only x is dual.
JACO_DUAL_FUNC dual jaco_interp1d(dual x, const double* xp, const double* yp, int n, int extrap) {
    if (x.val <= xp[0]) {
        if (extrap) {
            double slope = (yp[1] - yp[0]) / (xp[1] - xp[0]);
            return {yp[0] + slope * (x.val - xp[0]), slope * x.dot};
        }
        return {yp[0], 0.0};
    }
    if (x.val >= xp[n - 1]) {
        if (extrap) {
            double slope = (yp[n - 1] - yp[n - 2]) / (xp[n - 1] - xp[n - 2]);
            return {yp[n - 1] + slope * (x.val - xp[n - 1]), slope * x.dot};
        }
        return {yp[n - 1], 0.0};
    }
    int lo = 0, hi = n - 1;
    while (hi - lo > 1) {
        int mid = (lo + hi) / 2;
        if (xp[mid] <= x.val) lo = mid; else hi = mid;
    }
    double slope = (yp[hi] - yp[lo]) / (xp[hi] - xp[lo]);
    double t = (x.val - xp[lo]) / (xp[hi] - xp[lo]);
    return {yp[lo] + t * (yp[hi] - yp[lo]), slope * x.dot};
}

// Dual-aware interp without extrap flag (for CUDA clamp/extrap variants)
JACO_DUAL_FUNC dual jaco_interp1d_extrap(dual x, const double* xp, const double* yp, int n) {
    return jaco_interp1d(x, xp, yp, n, 1);
}
JACO_DUAL_FUNC dual jaco_interp1d_clamp(dual x, const double* xp, const double* yp, int n) {
    return jaco_interp1d(x, xp, yp, n, 0);
}

// --- Dual-aware 2D table interpolation ---
// x0, x1 are dual; the table struct contains plain doubles.

#include "jaco_table.h"

JACO_DUAL_FUNC dual jaco_table2d_interp(dual x0, dual x1, const JacoTable2D* t) {
    // Map to normalized coordinates
    double v0 = t->log0 ? std::log(x0.val) : x0.val;
    double v1 = t->log1 ? std::log(x1.val) : x1.val;
    double lo0 = t->log0 ? std::log(t->min0) : t->min0;
    double hi0 = t->log0 ? std::log(t->max0) : t->max0;
    double lo1 = t->log1 ? std::log(t->min1) : t->min1;
    double hi1 = t->log1 ? std::log(t->max1) : t->max1;

    double dx = (hi0 - lo0) / (t->n0 - 1);
    double dy = (hi1 - lo1) / (t->n1 - 1);
    double fx = (v0 - lo0) / dx;
    double fy = (v1 - lo1) / dy;

    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    double tx = fx - ix;
    double ty = fy - iy;

    double f00 = t->data[ix * t->n1 + iy];
    double f10 = t->data[(ix + 1) * t->n1 + iy];
    double f01 = t->data[ix * t->n1 + (iy + 1)];
    double f11 = t->data[(ix + 1) * t->n1 + (iy + 1)];

    double val = (1-tx)*(1-ty)*f00 + tx*(1-ty)*f10 + (1-tx)*ty*f01 + tx*ty*f11;

    // Partial derivatives of the bilinear formula w.r.t. normalized coords
    double df_dtx = -(1-ty)*f00 + (1-ty)*f10 - ty*f01 + ty*f11;
    double df_dty = -(1-tx)*f00 - tx*f10 + (1-tx)*f01 + tx*f11;

    // Chain rule: d(val)/d(x0) = df_dtx / dx * dv0/dx0
    double dv0_dx0 = t->log0 ? 1.0 / x0.val : 1.0;
    double dv1_dx1 = t->log1 ? 1.0 / x1.val : 1.0;

    double dot = (df_dtx / dx * dv0_dx0) * x0.dot
               + (df_dty / dy * dv1_dx1) * x1.dot;

    return {val, dot};
}

JACO_DUAL_FUNC dual jaco_table3d_interp(dual x0, dual x1, dual x2, const JacoTable3D* t) {
    double v0 = t->log0 ? std::log(x0.val) : x0.val;
    double v1 = t->log1 ? std::log(x1.val) : x1.val;
    double v2 = t->log2 ? std::log(x2.val) : x2.val;
    double lo0 = t->log0 ? std::log(t->min0) : t->min0;
    double hi0 = t->log0 ? std::log(t->max0) : t->max0;
    double lo1 = t->log1 ? std::log(t->min1) : t->min1;
    double hi1 = t->log1 ? std::log(t->max1) : t->max1;
    double lo2 = t->log2 ? std::log(t->min2) : t->min2;
    double hi2 = t->log2 ? std::log(t->max2) : t->max2;

    double dx = (hi0 - lo0) / (t->n0 - 1);
    double dy = (hi1 - lo1) / (t->n1 - 1);
    double dz = (hi2 - lo2) / (t->n2 - 1);
    double fx = (v0 - lo0) / dx;
    double fy = (v1 - lo1) / dy;
    double fz = (v2 - lo2) / dz;

    if (fx < 0) fx = 0; if (fx > t->n0 - 1) fx = t->n0 - 1;
    if (fy < 0) fy = 0; if (fy > t->n1 - 1) fy = t->n1 - 1;
    if (fz < 0) fz = 0; if (fz > t->n2 - 1) fz = t->n2 - 1;

    int ix = (int)fx; if (ix >= t->n0 - 1) ix = t->n0 - 2;
    int iy = (int)fy; if (iy >= t->n1 - 1) iy = t->n1 - 2;
    int iz = (int)fz; if (iz >= t->n2 - 1) iz = t->n2 - 2;
    double tx = fx - ix, ty = fy - iy, tz = fz - iz;

    int s1 = t->n2, s0 = t->n1 * t->n2;
    #define D(i,j,k) t->data[(ix+(i))*s0 + (iy+(j))*s1 + (iz+(k))]
    double val =
        (1-tx)*(1-ty)*(1-tz)*D(0,0,0) + tx*(1-ty)*(1-tz)*D(1,0,0)
      + (1-tx)*ty*(1-tz)*D(0,1,0)     + tx*ty*(1-tz)*D(1,1,0)
      + (1-tx)*(1-ty)*tz*D(0,0,1)     + tx*(1-ty)*tz*D(1,0,1)
      + (1-tx)*ty*tz*D(0,1,1)         + tx*ty*tz*D(1,1,1);

    // Partial derivatives w.r.t. normalized coords
    double df_dtx =
        -(1-ty)*(1-tz)*D(0,0,0) + (1-ty)*(1-tz)*D(1,0,0)
      - ty*(1-tz)*D(0,1,0)      + ty*(1-tz)*D(1,1,0)
      - (1-ty)*tz*D(0,0,1)      + (1-ty)*tz*D(1,0,1)
      - ty*tz*D(0,1,1)          + ty*tz*D(1,1,1);
    double df_dty =
        -(1-tx)*(1-tz)*D(0,0,0) - tx*(1-tz)*D(1,0,0)
      + (1-tx)*(1-tz)*D(0,1,0)  + tx*(1-tz)*D(1,1,0)
      - (1-tx)*tz*D(0,0,1)      - tx*tz*D(1,0,1)
      + (1-tx)*tz*D(0,1,1)      + tx*tz*D(1,1,1);
    double df_dtz =
        -(1-tx)*(1-ty)*D(0,0,0) - tx*(1-ty)*D(1,0,0)
      - (1-tx)*ty*D(0,1,0)      - tx*ty*D(1,1,0)
      + (1-tx)*(1-ty)*D(0,0,1)  + tx*(1-ty)*D(1,0,1)
      + (1-tx)*ty*D(0,1,1)      + tx*ty*D(1,1,1);
    #undef D

    double dv0 = t->log0 ? 1.0 / x0.val : 1.0;
    double dv1 = t->log1 ? 1.0 / x1.val : 1.0;
    double dv2 = t->log2 ? 1.0 / x2.val : 1.0;

    double dot = (df_dtx / dx * dv0) * x0.dot
               + (df_dty / dy * dv1) * x1.dot
               + (df_dtz / dz * dv2) * x2.dot;

    return {val, dot};
}
